# Generated by Django 5.2.7 on 2025-11-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Heavy_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='heavyuser',
            table='heavy_app_heavyuser',
        ),
    ]
